# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarcelFrameworks' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MarcelFrameworks
  pod 'Alamofire', '~> 4.8.2'

  target 'MarcelFrameworksTests' do
    inherit! :search_paths
    # Pods for testing
  pod 'Nimble'
  pod 'Quick'
  end

end
